// packages/projects/components/project-card/project-card.tsx
import React from 'react';
import { getProjectById } from 'utils/projects';
import dayjs from 'dayjs';
import Link from 'next/link';
import Skeleton from 'react-loading-skeleton';
import { ProjectActiveCapsule, ProjectActiveLinkTree } from './project-active';

interface ProjectCardProps {
    projectId: string;
}

export const ProjectCard = (async (props: ProjectCardProps) => {

  const {data} = await getProjectById(props.projectId);

  if (data) {
     return <div><Link href={'/project/' + props.projectId + '/home'}>
      <div className="flex items-center gap-2 cursor-pointer relative">
            <ProjectActiveCapsule projectId={props.projectId} />
            <div className="flex justify-between items-center w-full">
              <div className="flex gap-4 items-center">
                <span className="bg-center bg-cover h-[54px] w-[54px] rounded-xl" style={{backgroundImage: 'url('+ data.project_icon_url +')'}}></span>
                <div className="flex flex-col gap-px">
                  <h1 className="text-white-100 text-body-l font-normal font-display">{ data.name }</h1>
                  <span className="text-white-48 text-pretitle-s font-medium font-display">Crée le { dayjs(data.created_at).format('DD/MM/YY') }</span>
                </div>
              </div>
              <div className="notifications flex gap-2 items-center">
                <i className="fi fi-rr-settings h-4.5 w-4 flex items-center"></i>
              </div>
            </div>
        </div>
      </Link>
      <ProjectActiveLinkTree projectId={props.projectId} />
      </div>; 
  }

  return false;
}) as unknown as (props: ProjectCardProps) => JSX.Element;

export const ProjectCardSkeleton = () => {
  return <div className='flex items-center gap-2 cursor-pointer relative'>
      <div className='flex justify-between items-center w-full'>
        <div className='flex gap-4 items-center'>
          <Skeleton className='bg-center bg-cover !h-[54px] !w-[54px] rounded-xl'/>
          <div className='flex flex-col gap-px'>
            <Skeleton width={100}/>
            <Skeleton width={50}/>
          </div>
        </div>
        <Skeleton className='!h-4.5 !w-4 flex items-center'/>
      </div>
  </div>
};

// libs/shared/ui/src/lib/project-card/project-card.component.ts
import {Component, Input, OnInit, ViewEncapsulation} from '@angular/core';
import {JobService} from "@setbrain-dashboard/shared/data-access/users";

interface Project {
  id: string;
  name: string;
  created_at: Date;
  end_date: Date;
  project_icon_url: string;
}

@Component({
  selector: 'setbrain-dashboard-project-card',
  templateUrl: './project-card.component.html',
  styleUrls: ['./project-card.component.scss'],
  encapsulation: ViewEncapsulation.None,
})
export class ProjectCardComponent implements OnInit {
  @Input() project!: Project;
  @Input() projectNotifications: number | undefined;
  @Input() active = false;
  isAdmin= false;

  constructor(public job: JobService) {}

  ngOnInit() {
    this.job.isAdmin().then(admin => this.isAdmin = admin as unknown as boolean);
  }
}

<div class="flex items-center gap-2 cursor-pointer">
  <span class="h-5 w-[3px] bg-white-100 rounded-full shadow-[0px_0px_8px_rgba(255,255,255,0.5)]" *ngIf="active"></span>
  <div class="flex justify-between items-center w-full">
    <div class="flex gap-4 items-center">
      <span class="bg-center bg-cover h-[54px] w-[54px] rounded-xl" [ngStyle]="{backgroundImage: 'url(' + project.project_icon_url + ')'}"></span>
      <div class="flex flex-col gap-px">
        <h1 class="text-white-100 text-body-l font-normal">{{ project.name }}</h1>
        <span class="text-white-48 text-pretitle-s font-medium">Crée le {{ project.created_at | date:'dd/MM/YY' }}</span>
      </div>
    </div>
    <div class="notifications flex gap-2 items-center">
      <i class="fi fi-rr-settings h-4.5 w-4 flex items-center" *ngIf="isAdmin === true"></i>
      <span class="py-px px-2.5 bg-white-100 rounded-md text-black-100 text-body-sb font-bold" *ngIf="projectNotifications">{{ projectNotifications }}</span>
    </div>
  </div>
</div>
