// libs/shared/ui/src/lib/task-card/task-card.component.ts
import {Component, Input, OnInit, ViewEncapsulation} from '@angular/core';
import {Profile, ProfileService} from "@setbrain-dashboard/shared/data-access/users";
import {Task} from '@setbrain-dashboard/shared/data-access/tasks';

@Component({
  selector: 'setbrain-dashboard-task-card',
  templateUrl: './task-card.component.html',
  styleUrls: ['./task-card.component.scss'],
  encapsulation: ViewEncapsulation.None,
})
export class TaskCardComponent implements OnInit{
  @Input() task!: Task;
  assignedUsers: Profile[] | undefined;
  connectedUser!: Profile;

  constructor(public profileService: ProfileService) {}

  async ngOnInit() {
    this.assignedUsers = this.task.assigned_users as Profile[];
    this.profileService.profile.then(profile => this.connectedUser = profile as unknown as Profile);
  }
}

<div class="flex flex-col justify-between border-2 border-darkgrey-48 rounded-3xl bg-darkgrey-100 py-3 px-4 w-80 h-[13.5rem] cursor-pointer hover:border-darkgrey-86">
  <div class="card-top flex justify-between items-end">
    <setbrain-dashboard-tag [tagType]="task.type"></setbrain-dashboard-tag>
    <setbrain-dashboard-users-list [users]="assignedUsers" [connectedUser]="connectedUser"></setbrain-dashboard-users-list>
  </div>
  <div class="card-center flex flex-col gap-2 mt-2">
    <div class="flex gap-1 flex-col">
      <h1 class="font-bold text-body-lb text-white-100 w-52">{{task.title}}</h1>
      <span class="text-body-s text-white-48">Pour le {{task.end_at | date:'dd/MM/YY'}}</span>
    </div>
    <setbrain-dashboard-progressbar [progress]="task.progress" [endDate]="task.end_at"></setbrain-dashboard-progressbar>
  </div>
  <div class="card-bottom flex justify-between mt-3">
    <div class="flex gap-3">
      <span *ngIf="task.comments && task.comments.length > 0" class="text-pretitle flex items-center gap-1"><i class="fi fi-rr-comment-alt text-white-100 text-body-l"></i> {{task.comments.length}}</span>
      <span *ngIf="task.comments && task.joined_files.length > 0" class="text-pretitle flex items-center gap-1"><i class="fi fi-rr-clip text-white-100 text-body-l"></i> {{task.joined_files.length}}</span>
    </div>
    <a class="font-bold text-white-100 text-body-b">Voir plus</a>
  </div>
</div>

// packages/tasks/components/task-card.tsx
import dayjs from 'dayjs';
import React from 'react';
import { Skeleton } from 'ui';
import { Task } from 'types/database';
import { ProgressBar } from 'ui';
import { getColorByUrgency } from 'utils/tasks';

import {
    ProfilePictureList,
    ProfilePictureListSkeleton,
} from '../../auth/components/profile-picture-list';

interface TaskCardProps {
    task: Task;
}

export const TaskCard = ({ task }: TaskCardProps) => {
    return (
        <div className="flex flex-col justify-between border-2 rounded-2xl border-darkgrey-48 bg-darkgrey-100 py-3 px-4 w-full min-w-[300px] max-w-[345px] h-[13.5rem] cursor-pointer hover:border-darkgrey-86">
            <div className="flex justify-between items-end">
                <div className="px-1 py-0.5 bg-white-72 rounded-md w-fit text-pretitle font-medium text-black-100">
                    {task.type && task.type.toUpperCase()}
                </div>
                <span className="h-6">
                    <ProfilePictureList
                        ids={task.assigned_users ?? []}
                    ></ProfilePictureList>
                </span>
            </div>
            <div className="flex flex-col gap-2 mt-2">
                <div className="flex gap-1 flex-col">
                    <h1 className="font-bold text-body-lb text-white-100 w-52">
                        {task.title}
                    </h1>
                    <span className="text-body-s text-white-48">
                        Pour le {dayjs(task.end_at).format('DD/MM/YY')}
                    </span>
                </div>
                <ProgressBar
                    progress={task.progress * 100}
                    max={100}
                    intent={getColorByUrgency(task.end_at ?? '', task.progress)}
                ></ProgressBar>
            </div>
            <div className="flex justify-between mt-3">
                <div className="flex gap-3">
                    <span className="text-pretitle flex items-center gap-1">
                        <i className="fi fi-rr-comment-alt text-white-100 text-body-l"></i>{' '}
                        {task.comments?.length ?? 0}
                    </span>
                    <span className="text-pretitle flex items-center gap-1">
                        <i className="fi fi-rr-clip text-white-100 text-body-l"></i>{' '}
                        {task.joined_files?.length ?? 0}
                    </span>
                </div>
                <a className="font-bold text-white-100 text-body-b">
                    Voir plus
                </a>
            </div>
        </div>
    );
};

export const TaskCardSkeleton = () => {
    return (
        <div className="flex flex-col justify-between border-2 rounded-2xl border-darkgrey-48 bg-darkgrey-100 py-3 px-4 w-full min-w-[300px] max-w-[345px] h-[13.5rem] cursor-pointer hover:border-darkgrey-86">
            <div className="flex justify-between items-end w-full">
                <Skeleton height={25} width={50}></Skeleton>
                <span className="w-16">
                    <ProfilePictureListSkeleton />
                </span>
            </div>
            <div className="flex flex-col gap-2">
                <div className="flex gap-1 flex-col">
                    <Skeleton height={25} width={250}></Skeleton>
                    <Skeleton height={25} width={150}></Skeleton>
                    <Skeleton height={10} width={100}></Skeleton>
                </div>
                <Skeleton height={40} width={'100%'}></Skeleton>
            </div>
        </div>
    );
};
